### ISSUE TITLE
Autoconfiguration broken for Spring Boot 3.0

### ISSUE THREAD

**Issue by blulic** [rgielen/javafx-weaver#24]
For spring-boot-starter dependency, autoconfiguration is broken from Spring Boot 3.0.
Support for new autoconfiguration was [introduced in Spring Boot 2.7](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#changes-to-auto-configuration) with the backward compatibility with the old auto-configuration approach via spring.factories.

From [Spring Boot 3.0 support for spring.factories autoconfiguration](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files) was removed in favor of a new way.
Practically project requires a META-INF.spring directory with the file org.springframework.boot.autoconfigure.AutoConfiguration.imports and content: net.rgielen.fxweaver.spring.boot.autoconfigure.FxWeaverAutoConfiguration

I you agree, I could submit a PR with the fix for this, together with the dependency updates (Spring Boot 2.7 to support existing projects?).

**Comment by rgielen** [comment]
Yes, please go ahead. I didn't have much time lately, but it's definitely time for a new release. This issue is super crucial for further usability, indeed.

**Comment by rgielen** [comment]
Thanks for the patch, I'm going to merge it the next few days. Sorry for being a bit busy 😆
